version: "3"

services:
  node:
    build: ../node
    ports:
      - "3000:80"
    depends_on:
      - python
    environment:
      - BINANCE_KEY
      - BINANCE_SECRET
      - PYTHON_API=http://python:80
    volumes:
      - logs-volume:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  python:
    build: ../python
    ports:
      - "3001:80"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


volumes:
  logs-volume:
